### ISSUE TITLE
File extension: .rs (of course)

### ISSUE THREAD

**Issue by zeg-io** [dylanbeattie/rockstar#93] opened 2018-07-26 15:57 UTC
Proposal: The following should be valid Rockstar file extensions:

```
.rs
.rockstar
.track
```

**Comment by wolfgang42** [comment] 2018-07-26 16:09
Duplicate of #44. `.rs` is already taken by Rust, which we probably don't want to try to commandeer. `.track` is a new one.

**Comment by dylanbeattie** [comment] 2018-07-27 13:22
File extension is `.rock` : https://github.com/dylanbeattie/rockstar/commit/d7300d6502b72b150819dfb799128524e24bb313

**Closed by dylanbeattie** 2018-07-27 13:22 UTC
