### ISSUE TITLE
Inconsistency regarding single quote characters

### ISSUE THREAD

**Issue by tamias** [dylanbeattie/rockstar#73] opened 2018-07-24 17:15 UTC
Under 'Literals and Assignments', the README says that "The single quote character in Rockstar is treated as a letter of the alphabet."

Later, under 'Poetic Number Literals', one of the examples is:
`My dreams were ice. A life unfulfilled; wakin' everybody up, taking booze and pills` - initialises `my dreams` with the value `3.1415926535`

If the single quote is a letter of the alphabet, then `wakin'` should result in the digit `6`, not `5`.

**Comment by erikcorry** [comment] 2018-07-24 21:19
Dupe of #45

**Comment by dylanbeattie** [comment] 2018-07-25 19:49
Clarified docs in https://github.com/dylanbeattie/rockstar/commit/76d9ccc4031e128e0a2e486ba60d00fa1d89d916

Single quotes are valid characters in variable names and keywords, but are ignored in poetic literals.

**Closed by dylanbeattie** 2018-07-25 19:49 UTC
