### ISSUE TITLE
Not so sure about else

### ISSUE THREAD

**Issue by yanorestes** [dylanbeattie/rockstar#74] opened 2018-07-24 17:36 UTC
Else is just the keyword alone in the line?

```
If Midnight taking my world, Fire is nothing
Shout "Fizz!"
Take it to the top
Else
Shout "Else block!"
```

If so, it should have an alias for "Or else", it sounds a bit better given the context of the language

**Comment by dylanbeattie** [comment] 2018-07-25 19:34
Closing this as a duplicate of #50 - we'll pick it up there.

**Closed by dylanbeattie** 2018-07-25 19:34 UTC
